# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy - Production
on:
  workflow_dispatch:

jobs:
  call-reusable-build-and-deploy:
    uses: ./.github/workflows/template-build-deploy.yml
    with:
      environment: 'Production'
      AzureWebAppName: 'ssw-rulesgpt-api'
    
    secrets:
      AzureWebAppSecret: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1FEDFC8C3C4A497399C6318E5C173C42 }}
      AzureStaticWebAppsApiToken: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_DESERT_00E3FB600 }}
      GithubRepoToken: ${{ secrets.GITHUB_TOKEN }}