name: Build and Deploy - Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-build-and-deploy:
    uses: ./.github/workflows/template-build-deploy.yml
    with:
      githubEnvironment: 'Staging'
      deployEnvironment: 'stage'
      
      AzureWebAppName: ${{ vars.AZURE_WEB_APP_NAME }}
      AzureStaticWebAppName: ${{ vars.AZURE_STATIC_WEB_APP_NAME }}
      
      AppName: ${{ vars.APP_NAME }}
      
      hostingPlanName: ${{ vars.HOSTING_PLAN_NAME }}
      hostingPlanRgName: ${{ vars.HOSTING_PLAN_RG_NAME }}
    
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      AZURE_RG: ${{ secrets.AZURE_RG }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      
      ConnectionString: ${{ secrets.CONNECTION_STRING }}
      OpenAiApiKey: ${{ secrets.OPENAI_API_KEY }}
      
      GithubRepoToken: ${{ secrets.GITHUB_TOKEN }}