name: Build and Deploy - Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-reusable-build-and-deploy:
    uses: ./.github/workflows/template-build-deploy.yml
    with:
      githubEnvironment: 'Staging'
      deployEnvironment: 'stage'
      
      AppName: ${{ vars.APP_NAME }}
    
    secrets:
      AZURE_TENANT: ${{ secrets.AZURE_TENANT }}
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      AZURE_RG: ${{ secrets.AZURE_RG }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      
      ConnectionString: ${{ secrets.CONNECTION_STRING }}
      OpenAiApiKey: ${{ secrets.OPENAI_API_KEY }}

      GH_PAT: ${{ secrets.GH_PAT }}
      
      GithubRepoToken: ${{ secrets.GITHUB_TOKEN }}