name: Build and Deploy - Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-build-and-deploy:
    uses: ./.github/workflows/template-build-deploy.yml
    with:
      environment: 'Staging'
      
      AllowedCors: ${{ vars.AllowedCors }}
      MaxRequests: ${{ vars.MaxRequests }}
      SigningAuthority: ${{ vars.SigningAuthority }}
      
      AzureWebAppName: 'api-rulesgpt-stage'
      AzureStaticWebAppName: 'frontend-rulesgpt-stage'
    
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      AZURE_RG: ${{ secrets.AZURE_RG }}
      
      ConnectionString: ${{ secrets.ConnectionString }}
      OpenAiApiKey: ${{ secrets.OpenAiApiKey }}
      
      GithubRepoToken: ${{ secrets.GITHUB_TOKEN }}